# ============================================================
# Default compose file -> production
#   docker compose up --build -d
#
# Dev:
#   docker compose -f docker-compose.dev.yml up
# ============================================================

include:
  - docker-compose.prod.yml
